-- MySQL Script generated by MySQL Workbench
-- Mon Mar  4 16:58:05 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema lab_mysql
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lab_mysql
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lab_mysql` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `lab_mysql` ;

-- -----------------------------------------------------
-- Table `lab_mysql`.`cars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab_mysql`.`cars` (
  `car_id` INT NOT NULL AUTO_INCREMENT,
  `vin` VARCHAR(255) NULL DEFAULT NULL,
  `manufacturer` VARCHAR(255) NULL DEFAULT NULL,
  `model` VARCHAR(255) NULL DEFAULT NULL,
  `year_of_purcharse` YEAR NULL DEFAULT NULL,
  `color` VARCHAR(100) NULL DEFAULT NULL,
  `type_car` INT NULL DEFAULT NULL,
  `type_insurance` INT NULL DEFAULT NULL,
  PRIMARY KEY (`car_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `lab_mysql`.`invoices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab_mysql`.`invoices` (
  `invoice_number` INT NOT NULL AUTO_INCREMENT,
  `cust_id` INT NULL DEFAULT NULL,
  `staff_id` INT NULL DEFAULT NULL,
  `invoice_date` DATE NULL DEFAULT NULL,
  `number_cars` INT NULL DEFAULT NULL,
  `cars_car_id` INT NOT NULL,
  PRIMARY KEY (`invoice_number`),
  INDEX `fk_invoices_cars1_idx` (`cars_car_id` ASC) VISIBLE,
  CONSTRAINT `fk_invoices_cars1`
    FOREIGN KEY (`cars_car_id`)
    REFERENCES `lab_mysql`.`cars` (`car_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 39
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `lab_mysql`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab_mysql`.`customers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cust_id` INT NULL DEFAULT NULL,
  `name_id` VARCHAR(255) NULL DEFAULT NULL,
  `cust_phone` VARCHAR(13) NULL DEFAULT NULL,
  `cust_address` VARCHAR(255) NULL DEFAULT NULL,
  `cust_email` VARCHAR(255) NULL DEFAULT NULL,
  `cust_city` VARCHAR(255) NULL DEFAULT NULL,
  `date_of_contract` DATE NULL DEFAULT NULL,
  `cars_car_id` INT NOT NULL,
  `invoices_invoice_number` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_customers_cars1_idx` (`cars_car_id` ASC) VISIBLE,
  INDEX `fk_customers_invoices1_idx` (`invoices_invoice_number` ASC) VISIBLE,
  CONSTRAINT `fk_customers_cars1`
    FOREIGN KEY (`cars_car_id`)
    REFERENCES `lab_mysql`.`cars` (`car_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customers_invoices1`
    FOREIGN KEY (`invoices_invoice_number`)
    REFERENCES `lab_mysql`.`invoices` (`invoice_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `lab_mysql`.`sales_person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab_mysql`.`sales_person` (
  `staff_id` INT NOT NULL AUTO_INCREMENT,
  `agent_name` VARCHAR(255) NULL DEFAULT NULL,
  `agent_store` VARCHAR(255) NULL DEFAULT NULL,
  `agent_email` VARCHAR(255) NULL DEFAULT NULL,
  `agent_phone` VARCHAR(13) NULL DEFAULT NULL,
  `customers_id` INT NOT NULL,
  `invoices_invoice_number` INT NOT NULL,
  PRIMARY KEY (`staff_id`),
  INDEX `fk_sales_person_customers_idx` (`customers_id` ASC) VISIBLE,
  INDEX `fk_sales_person_invoices1_idx` (`invoices_invoice_number` ASC) VISIBLE,
  CONSTRAINT `fk_sales_person_customers`
    FOREIGN KEY (`customers_id`)
    REFERENCES `lab_mysql`.`customers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sales_person_invoices1`
    FOREIGN KEY (`invoices_invoice_number`)
    REFERENCES `lab_mysql`.`invoices` (`invoice_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO customers(id, cust_id, name_id, cust_phone, cust_address, cust_email, cust_city, date_of_contract) VALUES
("001", "101", "Antonio Sangroniz", "965236515", "C/Toleana", "asngroniz@gmail.com", "Valencia", "2001-01-01"),
("002", "102", "Jude Bellingan", "962456897", "C/Madrid", "judebelli@gmail.com", "Madrid", "2001-01-11"),
("003", "103", "Marcos Capone", "555698723", "C/Ironhack", "marcos_capone@gmail.com", "Barcelona", "2010-05-20");

INSERT INTO customers(id, cust_id, name_id, cust_phone, cust_address, cust_email, cust_city, date_of_contract) 
VALUES 
    ("004", "104", "Maria Gonzalez", "654789321", "C/Calle Mayor", "mariagonzalez@example.com", "Madrid", "2005-10-15"), 
    ("005", "105", "John Smith", "789456123", "123 Main St", "john.smith@example.com", "New York", "2003-07-20"), 
    ("006", "106", "Sophie Martin", "456987321", "5 Rue de la Paix", "sophiemartin@example.com", "Paris", "2008-04-30"),
    ("007", "107", "Luis Hernandez", "987654321", "Av. Libertador", "luishernandez@example.com", "Buenos Aires", "2012-12-05"),
    ("008", "108", "Emily Johnson", "369852147", "17 Baker Street", "emily.johnson@example.com", "London", "2006-09-28"),
    ("009", "109", "Andrea Rossi", "123987654", "Via Roma", "andrearossi@example.com", "Rome", "2009-11-10"),
    ("010", "110", "Juan Martinez", "456123789", "C/ Gran Vía", "juanmartinez@example.com", "Madrid", "2015-03-18"),
    ("011", "111", "Emma Wilson", "987654123", "21 Jump Street", "emma.wilson@example.com", "Los Angeles", "2018-06-25"),
    ("012", "112", "Luisa Fernandez", "654123987", "Av. Paulista", "luisafernandez@example.com", "São Paulo", "2013-08-12"),
    ("013", "113", "Mohammed Ali", "741852963", "King Abdulaziz Road", "mohammed.ali@example.com", "Dubai", "2011-02-14");

INSERT INTO cars(vin, manufacturer, model, year_of_purcharse, color, type_car, type_insurance) 
VALUES 
    ("1G1BL52P3TR121986", "Chevrolet", "Camaro", 2018, "Red", 1, 2), 
    ("WAUZZZ8K0AA140968", "Audi", "A4", 2019, "Black", 2, 3), 
    ("JM1NC2LF4K0309121", "Mazda", "MX-5", 2020, "Blue", 1, 1),
    ("5YJSA1E12JF285394", "Tesla", "Model S", 2017, "White", 3, 2),
    ("JHMFA36257S020181", "Honda", "Accord", 2015, "Silver", 2, 1),
    ("1HGCM66534A022352", "Honda", "Civic", 2016, "Gray", 2, 3),
    ("1FTFX1CF1BKD98983", "Ford", "F-150", 2021, "Black", 4, 2),
    ("1G6DH5EY3C0161644", "Cadillac", "CTS", 2014, "Red", 2, 1),
    ("1FA6P8CF0F5331157", "Ford", "Mustang", 2015, "Yellow", 1, 2),
    ("1J4BA6H18AL137493", "Jeep", "Wrangler", 2010, "Green", 4, 3),
    ("1GKET16S536219849", "GMC", "Envoy", 2005, "Silver", 4, 1),
    ("5NPDH4AE8CH148212", "Hyundai", "Elantra", 2012, "Blue", 2, 2),
    ("1C4RJEBG9FC238665", "Jeep", "Grand Cherokee", 2016, "White", 4, 3);
INSERT INTO sales_person(agent_name, agent_store, agent_email, agent_phone) 
VALUES 
    ("John Smith", "ABC Motors", "john.smith@example.com", "123-456-7890"),
    ("Maria Garcia", "XYZ Autos", "maria.garcia@example.com", "987-654-3210"),
    ("Michael Johnson", "Best Cars Inc.", "michael.johnson@example.com", "456-789-1230"),
    ("Emma Davis", "Sunset Motors", "emma.davis@example.com", "789-123-4560"),
    ("David Rodriguez", "City Auto Mall", "david.rodriguez@example.com", "321-654-9870"),
    ("Jennifer Martinez", "Quality Auto Sales", "jennifer.martinez@example.com", "654-987-3210"),
    ("Daniel Lee", "Top Cars LLC", "daniel.lee@example.com", "987-321-6540"),
    ("Sophia Nguyen", "Golden Wheels", "sophia.nguyen@example.com", "741-852-9630"),
    ("James Brown", "Premier Motors", "james.brown@example.com", "852-963-7410"),
    ("Olivia Hernandez", "Elite Auto Group", "olivia.hernandez@example.com", "369-258-1470"),
    ("William Taylor", "Luxury Auto", "william.taylor@example.com", "258-147-3690"),
    ("Ethan Wilson", "Speedy Motors", "ethan.wilson@example.com", "147-369-2580"),
    ("Ava Thomas", "Dream Cars", "ava.thomas@example.com", "963-852-7410");
INSERT INTO invoices(cust_id, staff_id, invoice_date, number_cars) 
VALUES 
    (101, 1, '2024-03-01', 2),
    (102, 2, '2024-03-02', 1),
    (103, 3, '2024-03-03', 3),
    (104, 4, '2024-03-04', 1),
    (105, 5, '2024-03-05', 2),
    (106, 6, '2024-03-06', 1),
    (107, 7, '2024-03-07', 3),
    (108, 8, '2024-03-08', 1),
    (109, 9, '2024-03-09', 2),
    (110, 10, '2024-03-10', 1),
    (111, 11, '2024-03-11', 3),
    (112, 12, '2024-03-12', 1),
    (113, 13, '2024-03-13', 2),
    (101, 1, '2024-03-14', 1),
    (102, 2, '2024-03-15', 2),
    (103, 3, '2024-03-16', 1),
    (104, 4, '2024-03-17', 3),
    (105, 5, '2024-03-18', 1),
    (106, 6, '2024-03-19', 2),
    (107, 7, '2024-03-20', 1),
    (108, 8, '2024-03-21', 3),
    (109, 9, '2024-03-22', 1),
    (110, 10, '2024-03-23', 2),
    (111, 11, '2024-03-24', 1),
    (112, 12, '2024-03-25', 3),
    (113, 13, '2024-03-26', 1),
    (101, 1, '2024-03-27', 2),
    (102, 2, '2024-03-28', 1),
    (103, 3, '2024-03-29', 3),
    (104, 4, '2024-03-30', 1),
    (105, 5, '2024-03-31', 2),
    (106, 6, '2024-04-01', 1),
    (107, 7, '2024-04-02', 3),
    (108, 8, '2024-04-03', 1),
    (109, 9, '2024-04-04', 2),
    (110, 10, '2024-04-05', 1),
    (111, 11, '2024-04-06', 3),
    (112, 12, '2024-04-07', 1);

 SELECT *
  FROM customers;
  
  SET SQL_SAFE_UPDATES = 0;
  
  UPDATE customers SET cust_email = "judebellighan@gmail.com" WHERE cust_email ="judebelli@gmail.com";
  
  
  SET SQL_SAFE_UPDATES = 1;
  
SELECT *
  FROM customers;
	SET SQL_SAFE_UPDATES = 0;
  
  DELETE FROM customers WHERE cust_id = "103";
  DELETE FROM customers WHERE cust_id = "105";
  DELETE FROM customers WHERE cust_id = "107";
  
  SET SQL_SAFE_UPDATES = 1;

  